baseurl: ''
url: 'https://vacacionesopitas.com'
name: 'Vacaciones Opitas'
author: Julian Franco
email: contacto@vacacionesopitas.com
# instagram: https://www.instagram.com/terminaldetransporte/
# twitter: https://twitter.com/bloglaterminal

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
